name: login

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Fazer checkout do repositório
      - uses: actions/checkout@v3

      # Etapa 2: Instalar dependências necessárias
      - name: Install Dependencies
        run: |
          sudo npm install -g newman
          sudo npm install -g newman-reporter-htmlextra

      # Etapa 3: Verificar versões do Newman e Node.js
      - name: Check versions of Newman and Node.js
        run: |
          newman --version
          node --version

      # Etapa 4: Executar a coleção do Newman
      - name: Execute Newman Collection
        run:
          newman run ./2_login.json -g ./globals.json -e ./Postman.json --delay-request 2000 --reporters cli,htmlextra --reporter-htmlextra-export ./result/report.html

      # Etapa 5: Arquivar o relatório gerado
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: ./result/report.html
